// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtrxSys.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MtrxSys.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MtrxDbContext))]
    [Migration("20260707175859_AddSendDeliveryAck")]
    partial class AddSendDeliveryAck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MtrxSys.Core.Domain.Campaigns.DispatchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<string>("ErrorReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_reason");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("WahaMessageId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("waha_message_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Status", "ScheduledAt");

                    b.ToTable("dispatch_jobs", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Contacts.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("GroupTag")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("group_tag");

                    b.Property<DateTimeOffset?>("LastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("OptInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opt_in_at");

                    b.Property<DateTimeOffset?>("OptOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opt_out_at");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset?>("StageChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stage_changed_at");

                    b.Property<string>("Theme")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("theme");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("GroupTag");

                    b.HasIndex("OptOutAt");

                    b.HasIndex("Stage");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Contacts.ContactNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("contact_notes", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Contacts.ContactStageChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<int?>("FromStage")
                        .HasColumnType("integer")
                        .HasColumnName("from_stage");

                    b.Property<int>("ToStage")
                        .HasColumnType("integer")
                        .HasColumnName("to_stage");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("contact_stage_changes", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Contacts.ContactTag", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Name");

                    b.ToTable("contact_tags", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Contacts.ContactTagAssignment", b =>
                {
                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<string>("TagName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tag_name");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("ContactId", "TagName");

                    b.HasIndex("TagName");

                    b.ToTable("contact_tag_assignments", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Conversations.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("author_phone");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("media_url");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("WaMessageId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("wa_message_id");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("WaMessageId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "Timestamp");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<string>("LastMessagePreview")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("last_message_preview");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("WaChatId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("wa_chat_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("LastMessageAt");

                    b.HasIndex("WaChatId")
                        .IsUnique();

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Groups.GroupLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<string>("GroupName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("group_name");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("invite_code");

                    b.Property<string>("InviteUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("invite_url");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("MatchedKeyword")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("matched_keyword");

                    b.Property<int?>("ParticipantCount")
                        .HasColumnType("integer")
                        .HasColumnName("participant_count");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("SourceChannel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source_channel");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("WhatsAppGroupId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("whatsapp_group_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("JoinedAt");

                    b.HasIndex("MatchedKeyword");

                    b.HasIndex("Status");

                    b.ToTable("group_links", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Messages.MessageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("ContentSpintax")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_spintax");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea")
                        .HasColumnName("image_data");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("text")
                        .HasColumnName("image_mime_type");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.HasKey("Id");

                    b.HasIndex("Slot", "Active");

                    b.ToTable("message_templates", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.SystemState.DailySendCount", b =>
                {
                    b.Property<DateOnly>("Id")
                        .HasColumnType("date")
                        .HasColumnName("date_utc");

                    b.Property<int>("SentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sent_count");

                    b.Property<int>("WarmupDayIndex")
                        .HasColumnType("integer")
                        .HasColumnName("warmup_day_index");

                    b.HasKey("Id");

                    b.ToTable("daily_send_counts", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.SystemState.SendAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ack");

                    b.Property<int>("DelayMs")
                        .HasColumnType("integer")
                        .HasColumnName("delay_ms");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("DispatchJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispatch_job_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_e164");

                    b.Property<string>("RenderedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rendered_text");

                    b.Property<int>("TypingMs")
                        .HasColumnType("integer")
                        .HasColumnName("typing_ms");

                    b.Property<string>("WaMessageId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("wa_message_id");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("WaMessageId");

                    b.ToTable("send_audit_log", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.SystemState.SystemStateAggregate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("DispatchMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("WahaOnly")
                        .HasColumnName("phone_dispatch_mode");

                    b.Property<string>("PausedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("paused_reason");

                    b.Property<DateTimeOffset?>("PhonePrimaryLastOnlineUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_primary_last_online_utc");

                    b.Property<int>("WarmupBonusToday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("warmup_bonus_today");

                    b.Property<bool>("WarmupEngineEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("warmup_engine_enabled");

                    b.Property<DateOnly?>("WarmupOverrideDate")
                        .HasColumnType("date")
                        .HasColumnName("warmup_override_date");

                    b.Property<string>("WarmupPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("warmup_phone");

                    b.Property<DateOnly?>("WarmupStartedOn")
                        .HasColumnType("date")
                        .HasColumnName("warmup_started_on");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("system_state", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("password_hash");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Contacts.Contact", b =>
                {
                    b.OwnsOne("MtrxSys.Core.Domain.Contacts.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("E164")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone_e164");

                            b1.HasKey("ContactId");

                            b1.HasIndex("E164")
                                .IsUnique();

                            b1.ToTable("contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Contacts.ContactNote", b =>
                {
                    b.HasOne("MtrxSys.Core.Domain.Contacts.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Contacts.ContactStageChange", b =>
                {
                    b.HasOne("MtrxSys.Core.Domain.Contacts.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Contacts.ContactTagAssignment", b =>
                {
                    b.HasOne("MtrxSys.Core.Domain.Contacts.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtrxSys.Core.Domain.Contacts.ContactTag", null)
                        .WithMany()
                        .HasForeignKey("TagName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Conversations.ChatMessage", b =>
                {
                    b.HasOne("MtrxSys.Core.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.SystemState.SystemStateAggregate", b =>
                {
                    b.OwnsOne("MtrxSys.Core.Domain.SystemState.CircuitBreakerState", "Circuit", b1 =>
                        {
                            b1.Property<int>("SystemStateAggregateId")
                                .HasColumnType("integer");

                            b1.Property<int>("ConsecutiveFailures")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("consecutive_failures");

                            b1.Property<DateTimeOffset?>("OpenUntil")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("circuit_open_until");

                            b1.HasKey("SystemStateAggregateId");

                            b1.ToTable("system_state");

                            b1.WithOwner()
                                .HasForeignKey("SystemStateAggregateId");
                        });

                    b.Navigation("Circuit")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
