// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtrxSys.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MtrxSys.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MtrxDbContext))]
    [Migration("20260521133512_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MtrxSys.Core.Domain.Campaigns.DispatchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<string>("ErrorReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_reason");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("WahaMessageId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("waha_message_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ScheduledAt");

                    b.ToTable("dispatch_jobs", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Contacts.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GroupTag")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("group_tag");

                    b.Property<DateTimeOffset?>("LastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("OptInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opt_in_at");

                    b.Property<DateTimeOffset?>("OptOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opt_out_at");

                    b.Property<string>("Theme")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("theme");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Messages.MessageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("ContentSpintax")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_spintax");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.HasKey("Id");

                    b.HasIndex("Slot", "Active");

                    b.ToTable("message_templates", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.SystemState.DailySendCount", b =>
                {
                    b.Property<DateOnly>("Id")
                        .HasColumnType("date")
                        .HasColumnName("date_utc");

                    b.Property<int>("SentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sent_count");

                    b.Property<int>("WarmupDayIndex")
                        .HasColumnType("integer")
                        .HasColumnName("warmup_day_index");

                    b.HasKey("Id");

                    b.ToTable("daily_send_counts", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.SystemState.SendAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DelayMs")
                        .HasColumnType("integer")
                        .HasColumnName("delay_ms");

                    b.Property<Guid>("DispatchJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispatch_job_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_e164");

                    b.Property<string>("RenderedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rendered_text");

                    b.Property<int>("TypingMs")
                        .HasColumnType("integer")
                        .HasColumnName("typing_ms");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("send_audit_log", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.SystemState.SystemStateAggregate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("PausedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("paused_reason");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("system_state", (string)null);
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.Contacts.Contact", b =>
                {
                    b.OwnsOne("MtrxSys.Core.Domain.Contacts.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("uuid");

                            b1.Property<string>("E164")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone_e164");

                            b1.HasKey("ContactId");

                            b1.HasIndex("E164")
                                .IsUnique();

                            b1.ToTable("contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("MtrxSys.Core.Domain.SystemState.SystemStateAggregate", b =>
                {
                    b.OwnsOne("MtrxSys.Core.Domain.SystemState.CircuitBreakerState", "Circuit", b1 =>
                        {
                            b1.Property<int>("SystemStateAggregateId")
                                .HasColumnType("integer");

                            b1.Property<int>("ConsecutiveFailures")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("consecutive_failures");

                            b1.Property<DateTimeOffset?>("OpenUntil")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("circuit_open_until");

                            b1.HasKey("SystemStateAggregateId");

                            b1.ToTable("system_state");

                            b1.WithOwner()
                                .HasForeignKey("SystemStateAggregateId");
                        });

                    b.Navigation("Circuit")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
